### ISSUE TITLE
Fix broken generate pipeline stage

### ISSUE THREAD

**Issue by ianthetechie** [maplibre/maplibre-react-native#15]
See https://github.com/maplibre/maplibre-react-native/actions/runs/3733996724 for an example failed run.

My JS foo is not great enough to figure out why this is not working.

For what it's worth, this works perfectly fine locally, so I am not entirely sure how to go about debugging. I develop on an M1 Mac; should be the only relevant variable. The package uses yarn with pnp / zero installs, so everything except platform-native code and caches should be identical as the lockfiles and pnp js are all checked in. And we're using nvm, so node versions should align. Running `yarn generate` locally succeeds with a 0 exit status and no unhandled promise rejections.

This will block #2.

**Comment by jthiard** [comment]
This is an interesting one !

It looks like it has something to do with this code https://github.com/maplibre/maplibre-react-native/blob/445740da2a41ca50dcb6decbb1be89dc92a29e24/scripts/autogenHelpers/DocJSONBuilder.js#L393-L398

The first time it runs `npx` will install the `documentation` package (it does not use the one installed by yarn, since yarn v3 does not use the `node_modules` directory.

While installing the package it print a warning on stderr, and the above code trigger a promise rejection when it finds something in the child process stderr...

Following runs may be ok since the `documentation` package is already instaled in `~/.npm/_npx/`, thius is why you don't get this error on your local box.

2 fixes I may think about, each one may have some side effects.

1. use `yarn` instead of `npx` in this script
2. don't reject the promise in case of `stderr`

**Comment by ianthetechie** [comment]
Oh, wow... I'm still scratching my head as to how this worked before (maybe we just forked in a broken state), but I thought I had tried option 1 previously. Apparently not ;) Thanks so much for looking into this @jthiard!

**Comment by jthiard** [comment]
> I'm still scratching my head as to how this worked before (maybe we just forked in a broken state)

Was asking myself the same. I'm not very familiar with yarn "pnp" but the upstream repo may use yarn v1 (installed by default). With some luck npx is re-using the `documentation` package previously installed by yarn in the `node_modules` directory.

**Comment by ianthetechie** [comment]
That's a good point, and you're probably right. I think the upstream still is using yarn v1. I still can't figure out why this is installed by default, but I found it surprising enough to put in the README. v3 standard behavior makes a lot more sense to me (it's *way* faster and more reproducible)).

Thanks again for your help identifying the issue!
